# fly.toml app configuration file generated for cds2023-young-silence-2831-dawn-water-2968 on 2023-11-25T13:00:47-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cds2023-young-silence-2831-dawn-water-2968"
primary_region = "gdl"

[build]

[http_service]
  internal_port = 3000
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
